<%@ Page Title="" Language="C#" MasterPageFile="~/admin/Admin.Master" AutoEventWireup="true" CodeBehind="OrderProcessing.aspx.cs" Inherits="EBFRW_Web.admin.OrderProcessing" %>
<asp:Content ID="Content1" ContentPlaceHolderID="headContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainContent" runat="server">
                <asp:GridView ID="GridView1" runat="server" CellPadding="4"  AutoGenerateColumns="false"
    ForeColor="#333333" OnRowDeleting="GridView1_RowDeleting" AllowSorting="True" 
    AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" 
    AutoGenerateSelectButton="False" >
                <AlternatingRowStyle BackColor="White" />
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
                <Columns>
                    <asp:BoundField DataField="order_id" HeaderText="ORDER #" />
                    <asp:BoundField DataField="register_option" HeaderText="REG OPTION" />
                    <asp:BoundField DataField="membership_type" HeaderText="MEMB TYPE" />
                    <asp:BoundField DataField="fc_first_name" HeaderText="1ST F NAME" />
                    <asp:BoundField DataField="fc_last_name" HeaderText="1ST L NAME" />
                    <asp:BoundField DataField="fc_bday" HeaderText="1ST BDAY" />
                    <asp:BoundField DataField="fc_email" HeaderText="1ST EMAIL" />
                    <asp:BoundField DataField="fc_home_phone" HeaderText="1ST H PHONE" />
                    <asp:BoundField DataField="fc_cell_phone" HeaderText="1ST C PHONE" />
                    <asp:BoundField DataField="fc_work_phone" HeaderText="1ST W PHONE" />
                    <asp:BoundField DataField="sc_first_name" HeaderText="2ND F NAME" />
                    <asp:BoundField DataField="sc_last_name" HeaderText="2ND L NAME" />
                    <asp:BoundField DataField="sc_bday" HeaderText="2ND BDAY" />
                    <asp:BoundField DataField="sc_email" HeaderText="2ND EMAIL" />
                    <asp:BoundField DataField="sc_home_phone" HeaderText="2ND H PHONE" />
                    <asp:BoundField DataField="sc_cell_phone" HeaderText="2ND C PHONE" />
                    <asp:BoundField DataField="sc_work_phone" HeaderText="2ND W PHONE" />
                    <asp:BoundField DataField="street1" HeaderText="STREET" />
                    <asp:BoundField DataField="street2" HeaderText="APT" />
                    <asp:BoundField DataField="city" HeaderText="CITY" />
                    <asp:BoundField DataField="state" HeaderText="STATE" />
                    <asp:BoundField DataField="zip" HeaderText="ZIP" />
                    <asp:BoundField DataField="em_ct_first_name" HeaderText="EM CT FIRST NAME" />
                    <asp:BoundField DataField="em_ct_last_name" HeaderText="EM CT LAST NAME" />
                    <asp:BoundField DataField="em_ct_phone" HeaderText="EM CT PHONE" />
                    <asp:BoundField DataField="include_m_dir" HeaderText="INC DIR?" />
                    <asp:BoundField DataField="include_phone" HeaderText="INC PHONE" />
                    <asp:BoundField DataField="include_email" HeaderText="INC EMAIL?" />
                    <asp:BoundField DataField="include_home_address" HeaderText="INC ADDR?" />
                    <asp:BoundField DataField="use_photo_consent" HeaderText="USE PHOTO?" />
                    <asp:BoundField DataField="host_potluck" HeaderText="POTLUCK?" />
                    <asp:BoundField DataField="waiver_init" HeaderText="WAIVER" />

                </Columns>
            </asp:GridView>



</asp:Content>
